#!/usr/bin/env bash
# Configures localhost to resolve to 127.0.0.2 and facebook.com to 8.8.8.8

sed 's/^127\.0\.0\.1[[:space:]]\+localhost/127.0.0.2 localhost/' /etc/hosts > /tmp/hosts_new
echo "8.8.8.8 facebook.com" >> /tmp/hosts_new
cat /tmp/hosts_new > /etc/hosts
